//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shikashi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AuthKey {
            get {
                return ((string)(this["AuthKey"]));
            }
            set {
                this["AuthKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long AuthExpirationTime {
            get {
                return ((long)(this["AuthExpirationTime"]));
            }
            set {
                this["AuthExpirationTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentUser {
            get {
                return ((string)(this["CurrentUser"]));
            }
            set {
                this["CurrentUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118")]
        public int FullScreenshotHotkeyFirst {
            get {
                return ((int)(this["FullScreenshotHotkeyFirst"]));
            }
            set {
                this["FullScreenshotHotkeyFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FullScreenshotHotkeySecond {
            get {
                return ((int)(this["FullScreenshotHotkeySecond"]));
            }
            set {
                this["FullScreenshotHotkeySecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("116")]
        public int FullScreenshotHotkeyThird {
            get {
                return ((int)(this["FullScreenshotHotkeyThird"]));
            }
            set {
                this["FullScreenshotHotkeyThird"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37")]
        public int FullScreenshotHotkeyValue {
            get {
                return ((int)(this["FullScreenshotHotkeyValue"]));
            }
            set {
                this["FullScreenshotHotkeyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118")]
        public int RegionalScreenshotHotkeyFirst {
            get {
                return ((int)(this["RegionalScreenshotHotkeyFirst"]));
            }
            set {
                this["RegionalScreenshotHotkeyFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RegionalScreenshotHotkeySecond {
            get {
                return ((int)(this["RegionalScreenshotHotkeySecond"]));
            }
            set {
                this["RegionalScreenshotHotkeySecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("116")]
        public int RegionalScreenshotHotkeyThird {
            get {
                return ((int)(this["RegionalScreenshotHotkeyThird"]));
            }
            set {
                this["RegionalScreenshotHotkeyThird"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int RegionalScreenshotHotkeyValue {
            get {
                return ((int)(this["RegionalScreenshotHotkeyValue"]));
            }
            set {
                this["RegionalScreenshotHotkeyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118")]
        public int WindowedScreenshotHotkeyFirst {
            get {
                return ((int)(this["WindowedScreenshotHotkeyFirst"]));
            }
            set {
                this["WindowedScreenshotHotkeyFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowedScreenshotHotkeySecond {
            get {
                return ((int)(this["WindowedScreenshotHotkeySecond"]));
            }
            set {
                this["WindowedScreenshotHotkeySecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("116")]
        public int WindowedScreenshotHotkeyThird {
            get {
                return ((int)(this["WindowedScreenshotHotkeyThird"]));
            }
            set {
                this["WindowedScreenshotHotkeyThird"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public int WindowedScreenshotHotkeyValue {
            get {
                return ((int)(this["WindowedScreenshotHotkeyValue"]));
            }
            set {
                this["WindowedScreenshotHotkeyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveScreenshots {
            get {
                return ((bool)(this["SaveScreenshots"]));
            }
            set {
                this["SaveScreenshots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveFolder {
            get {
                return ((string)(this["SaveFolder"]));
            }
            set {
                this["SaveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SaveFormat {
            get {
                return ((int)(this["SaveFormat"]));
            }
            set {
                this["SaveFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int SaveQuality {
            get {
                return ((int)(this["SaveQuality"]));
            }
            set {
                this["SaveQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("png")]
        public string UploadFormat {
            get {
                return ((string)(this["UploadFormat"]));
            }
            set {
                this["UploadFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyLinksToClipboard {
            get {
                return ((bool)(this["CopyLinksToClipboard"]));
            }
            set {
                this["CopyLinksToClipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCursor {
            get {
                return ((bool)(this["ShowCursor"]));
            }
            set {
                this["ShowCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SoundEffects {
            get {
                return ((bool)(this["SoundEffects"]));
            }
            set {
                this["SoundEffects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BalloonMessages {
            get {
                return ((bool)(this["BalloonMessages"]));
            }
            set {
                this["BalloonMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LaunchBrowser {
            get {
                return ((bool)(this["LaunchBrowser"]));
            }
            set {
                this["LaunchBrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AskedForStartup {
            get {
                return ((bool)(this["AskedForStartup"]));
            }
            set {
                this["AskedForStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunAtStartup {
            get {
                return ((bool)(this["RunAtStartup"]));
            }
            set {
                this["RunAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseDarkTheme {
            get {
                return ((bool)(this["UseDarkTheme"]));
            }
            set {
                this["UseDarkTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SSLEnabled {
            get {
                return ((bool)(this["SSLEnabled"]));
            }
            set {
                this["SSLEnabled"] = value;
            }
        }
    }
}
